version: '3.8'

services:
  postgres_db:

    image: postgres:14-alpine
    container_name: neo_osi_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: neo_osi_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    container_name: neo_osi_libreoffice
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - "3001:3000"
    restart: unless-stopped

volumes:
  postgres_data:
